# Generated by Django 5.2.4 on 2025-07-25 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_a', models.CharField(max_length=100, verbose_name='Команда A')),
                ('team_b', models.CharField(max_length=100, verbose_name='Команда B')),
                ('date', models.DateTimeField(verbose_name='Дата матча')),
                ('score_a', models.IntegerField(blank=True, null=True, verbose_name='Голы команды A')),
                ('score_b', models.IntegerField(blank=True, null=True, verbose_name='Голы команды B')),
                ('is_finished', models.BooleanField(default=False, verbose_name='Матч завершён')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название команды')),
                ('points', models.IntegerField(default=0, verbose_name='Очки')),
                ('games_played', models.IntegerField(default=0, verbose_name='Игры')),
                ('wins', models.IntegerField(default=0, verbose_name='Победы')),
                ('draws', models.IntegerField(default=0, verbose_name='Ничьи')),
                ('losses', models.IntegerField(default=0, verbose_name='Поражения')),
                ('group', models.CharField(choices=[('A', 'Группа A'), ('B', 'Группа B')], max_length=1, verbose_name='Группа')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя игрока')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='players/', verbose_name='Фото')),
                ('goals', models.IntegerField(default=0, verbose_name='Голы')),
                ('assists', models.IntegerField(default=0, verbose_name='Ассисты')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.team', verbose_name='Команда')),
            ],
        ),
    ]
