# Generated by Django 5.2.4 on 2025-08-02 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_pagevisit'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='matches/'),
        ),
    ]
