# Generated by Django 5.2.4 on 2025-08-02 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_match_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='matches/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Изображение матча',
                'verbose_name_plural': 'Изображения матчей',
            },
        ),
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['date'], 'verbose_name': 'Матч', 'verbose_name_plural': 'Матчи'},
        ),
        migrations.AlterModelOptions(
            name='pagevisit',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Посещение', 'verbose_name_plural': 'Статистика посещений'},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['-goals', '-assists'], 'verbose_name': 'Игрок', 'verbose_name_plural': 'Игроки'},
        ),
        migrations.AlterModelOptions(
            name='sponsor',
            options={'ordering': ['-is_main', 'order'], 'verbose_name': 'Спонсор', 'verbose_name_plural': 'Спонсоры'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['-wins', '-draws', '-goals_for'], 'verbose_name': 'Команда', 'verbose_name_plural': 'Команды'},
        ),
        migrations.AlterModelOptions(
            name='videoreview',
            options={'ordering': ['-date'], 'verbose_name': 'Видеообзор', 'verbose_name_plural': 'Видеообзоры'},
        ),
        migrations.AddField(
            model_name='match',
            name='video_url',
            field=models.URLField(blank=True, verbose_name='Ссылка на видео'),
        ),
        migrations.AddField(
            model_name='pagevisit',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='player',
            name='number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Игровой номер'),
        ),
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('GK', 'Вратарь'), ('DF', 'Защитник'), ('MF', 'Полузащитник'), ('FW', 'Нападающий')], default='MF', max_length=2, verbose_name='Позиция'),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Генеральный спонсор'),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок отображения'),
        ),
        migrations.AddField(
            model_name='team',
            name='color',
            field=models.CharField(default='#000000', max_length=7, verbose_name='Цвет команды (HEX)'),
        ),
        migrations.AddField(
            model_name='team',
            name='short_name',
            field=models.CharField(default='TEA', max_length=3, verbose_name='Аббревиатура'),
        ),
        migrations.AddField(
            model_name='videoreview',
            name='match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.match', verbose_name='Связанный матч'),
        ),
        migrations.AlterField(
            model_name='match',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='matches/', verbose_name='Основное изображение'),
        ),
        migrations.AlterField(
            model_name='match',
            name='score_a',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Голы команды A'),
        ),
        migrations.AlterField(
            model_name='match',
            name='score_b',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Голы команды B'),
        ),
        migrations.AlterField(
            model_name='pagevisit',
            name='ip',
            field=models.GenericIPAddressField(verbose_name='IP адрес'),
        ),
        migrations.AlterField(
            model_name='pagevisit',
            name='path',
            field=models.CharField(max_length=255, verbose_name='Путь'),
        ),
        migrations.AlterField(
            model_name='pagevisit',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время визита'),
        ),
        migrations.AlterField(
            model_name='pagevisit',
            name='user_agent',
            field=models.TextField(blank=True, verbose_name='User Agent'),
        ),
        migrations.AlterField(
            model_name='player',
            name='assists',
            field=models.PositiveIntegerField(default=0, verbose_name='Голевые передачи'),
        ),
        migrations.AlterField(
            model_name='player',
            name='goals',
            field=models.PositiveIntegerField(default=0, verbose_name='Голы'),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Полное имя'),
        ),
        migrations.AlterField(
            model_name='player',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='players/', verbose_name='Фото игрока'),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='core.team', verbose_name='Команда'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='logo',
            field=models.ImageField(help_text='Рекомендуемый размер: 300x100 пикселей', upload_to='sponsors/', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название компании'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='url',
            field=models.URLField(verbose_name='Ссылка на сайт'),
        ),
        migrations.AlterField(
            model_name='team',
            name='draws',
            field=models.PositiveIntegerField(default=0, verbose_name='Ничьи'),
        ),
        migrations.AlterField(
            model_name='team',
            name='games_played',
            field=models.PositiveIntegerField(default=0, verbose_name='Сыграно матчей'),
        ),
        migrations.AlterField(
            model_name='team',
            name='goals_against',
            field=models.PositiveIntegerField(default=0, verbose_name='Пропущено голов'),
        ),
        migrations.AlterField(
            model_name='team',
            name='goals_for',
            field=models.PositiveIntegerField(default=0, verbose_name='Забито голов'),
        ),
        migrations.AlterField(
            model_name='team',
            name='losses',
            field=models.PositiveIntegerField(default=0, verbose_name='Поражения'),
        ),
        migrations.AlterField(
            model_name='team',
            name='wins',
            field=models.PositiveIntegerField(default=0, verbose_name='Победы'),
        ),
        migrations.AlterField(
            model_name='videoreview',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='videoreview',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название обзора'),
        ),
        migrations.AlterField(
            model_name='videoreview',
            name='youtube_id',
            field=models.CharField(help_text='Например: dQw4w9WgXcQ', max_length=20, verbose_name='ID видео на YouTube'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['date'], name='core_match_date_c24213_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['is_finished'], name='core_match_is_fini_0a51bb_idx'),
        ),
        migrations.AddIndex(
            model_name='pagevisit',
            index=models.Index(fields=['-timestamp'], name='core_pagevi_timesta_cc308b_idx'),
        ),
        migrations.AddIndex(
            model_name='pagevisit',
            index=models.Index(fields=['path'], name='core_pagevi_path_233470_idx'),
        ),
        migrations.AddField(
            model_name='matchimage',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.match'),
        ),
    ]
