# Generated by Django 5.2.4 on 2025-08-02 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_matchimage_alter_match_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchimage',
            name='match',
        ),
        migrations.AlterModelOptions(
            name='match',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pagevisit',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Посещение', 'verbose_name_plural': 'Посещения'},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sponsor',
            options={},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={},
        ),
        migrations.AlterModelOptions(
            name='videoreview',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='match',
            name='core_match_date_c24213_idx',
        ),
        migrations.RemoveIndex(
            model_name='match',
            name='core_match_is_fini_0a51bb_idx',
        ),
        migrations.RemoveIndex(
            model_name='pagevisit',
            name='core_pagevi_timesta_cc308b_idx',
        ),
        migrations.RemoveIndex(
            model_name='pagevisit',
            name='core_pagevi_path_233470_idx',
        ),
        migrations.RemoveField(
            model_name='match',
            name='video_url',
        ),
        migrations.RemoveField(
            model_name='pagevisit',
            name='user',
        ),
        migrations.RemoveField(
            model_name='player',
            name='number',
        ),
        migrations.RemoveField(
            model_name='player',
            name='position',
        ),
        migrations.RemoveField(
            model_name='sponsor',
            name='is_main',
        ),
        migrations.RemoveField(
            model_name='sponsor',
            name='order',
        ),
        migrations.RemoveField(
            model_name='team',
            name='color',
        ),
        migrations.RemoveField(
            model_name='team',
            name='short_name',
        ),
        migrations.RemoveField(
            model_name='videoreview',
            name='match',
        ),
        migrations.AlterField(
            model_name='match',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='matches/'),
        ),
        migrations.AlterField(
            model_name='match',
            name='score_a',
            field=models.IntegerField(blank=True, null=True, verbose_name='Голы команды A'),
        ),
        migrations.AlterField(
            model_name='match',
            name='score_b',
            field=models.IntegerField(blank=True, null=True, verbose_name='Голы команды B'),
        ),
        migrations.AlterField(
            model_name='pagevisit',
            name='ip',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pagevisit',
            name='path',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pagevisit',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pagevisit',
            name='user_agent',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='assists',
            field=models.IntegerField(default=0, verbose_name='Ассисты'),
        ),
        migrations.AlterField(
            model_name='player',
            name='goals',
            field=models.IntegerField(default=0, verbose_name='Голы'),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя игрока'),
        ),
        migrations.AlterField(
            model_name='player',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='players/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.team', verbose_name='Команда'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='logo',
            field=models.ImageField(upload_to='sponsors/'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='draws',
            field=models.IntegerField(default=0, verbose_name='Ничьи'),
        ),
        migrations.AlterField(
            model_name='team',
            name='games_played',
            field=models.IntegerField(default=0, verbose_name='Игры'),
        ),
        migrations.AlterField(
            model_name='team',
            name='goals_against',
            field=models.IntegerField(default=0, verbose_name='Пропущено'),
        ),
        migrations.AlterField(
            model_name='team',
            name='goals_for',
            field=models.IntegerField(default=0, verbose_name='Забито'),
        ),
        migrations.AlterField(
            model_name='team',
            name='losses',
            field=models.IntegerField(default=0, verbose_name='Поражения'),
        ),
        migrations.AlterField(
            model_name='team',
            name='wins',
            field=models.IntegerField(default=0, verbose_name='Победы'),
        ),
        migrations.AlterField(
            model_name='videoreview',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='videoreview',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='videoreview',
            name='youtube_id',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='MatchImage',
        ),
    ]
