# Generated by Django 5.2.4 on 2025-08-11 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_sliderimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Match',
        ),
    ]
