# Generated by Django 5.2.4 on 2025-08-11 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_delete_match'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matchday', models.CharField(choices=[('MD1', 'Matchday 1'), ('MD2', 'Matchday 2')], default='MD1', max_length=3)),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, help_text='Формат: HH:MM', null=True, verbose_name='Время матча')),
                ('venue', models.CharField(max_length=200)),
                ('team_a', models.CharField(max_length=100)),
                ('team_a_logo', models.ImageField(blank=True, null=True, upload_to='teams/logos/')),
                ('team_b', models.CharField(max_length=100)),
                ('team_b_logo', models.ImageField(blank=True, null=True, upload_to='teams/logos/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Matches',
                'ordering': ['date', 'time'],
            },
        ),
    ]
