# Generated by Django 5.2.4 on 2025-08-11 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='team_a_logo',
            field=models.ImageField(blank=True, null=True, upload_to='teams/matcheslogo/'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_b_logo',
            field=models.ImageField(blank=True, null=True, upload_to='teams/matcheslogo/'),
        ),
    ]
