# Generated by Django 5.2.4 on 2025-08-12 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_match_team_a_logo_alter_match_team_b_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MvpPlayers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='mvp_players/')),
                ('votes', models.PositiveIntegerField(default=0)),
                ('position', models.CharField(blank=True, max_length=50)),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.team')),
            ],
            options={
                'verbose_name': 'MVP игрок',
                'verbose_name_plural': 'MVP игроки',
                'ordering': ['-votes'],
            },
        ),
        migrations.CreateModel(
            name='VoteRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.mvpplayers')),
            ],
        ),
    ]
