# Generated by Django 4.0.6 on 2025-08-18 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_mvpplayers_voterecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='matchday',
            field=models.CharField(choices=[('MD1', 'Matchday 1'), ('MD2', 'Matchday 2'), ('MD2', 'Matchday 3'), ('MD2', 'Matchday 4'), ('MD2', 'Matchday 5'), ('MD2', 'Matchday 6'), ('MD2', 'Matchday 7'), ('MD2', 'Matchday 8'), ('MD2', 'Matchday 9')], default='MD1', max_length=3),
        ),
    ]
