# Generated by Django 5.2.4 on 2026-01-15 05:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_mvpplayers_voterecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='EMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_a', models.CharField(max_length=100, verbose_name='Команда A')),
                ('team_b', models.CharField(max_length=100, verbose_name='Команда B')),
                ('score_a', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)], verbose_name='Счет команды A')),
                ('score_b', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)], verbose_name='Счет команды B')),
                ('match_date', models.DateField(verbose_name='Дата матча')),
                ('match_time', models.TimeField(verbose_name='Время матча')),
                ('status', models.CharField(choices=[('upcoming', 'Предстоящий'), ('live', 'В прямом эфире'), ('completed', 'Завершен')], default='upcoming', max_length=10, verbose_name='Статус')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='Место проведения')),
                ('tournament_round', models.CharField(blank=True, max_length=100, null=True, verbose_name='Тур/раунд')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Матч',
                'verbose_name_plural': 'Матчи',
                'ordering': ['match_date', 'match_time'],
                'indexes': [models.Index(fields=['match_date'], name='core_ematch_match_d_4169d9_idx'), models.Index(fields=['status'], name='core_ematch_status_f99510_idx')],
            },
        ),
    ]
