# Generated by Django 6.0.6 on 2026-06-17 10:26

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_create_livematch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sponsor',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Партнёр', 'verbose_name_plural': 'Партнёры'},
        ),
        migrations.AlterModelOptions(
            name='videoreview',
            options={'ordering': ['order', '-date'], 'verbose_name': 'Видеообзор', 'verbose_name_plural': 'Видеообзоры'},
        ),
        migrations.AddField(
            model_name='sponsor',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='sponsor_type',
            field=models.CharField(choices=[('general', 'Генеральный партнёр'), ('official', 'Официальный партнёр')], default='official', max_length=10, verbose_name='Тип партнёра'),
        ),
        migrations.AddField(
            model_name='videoreview',
            name='category',
            field=models.CharField(choices=[('highlights', 'Match Highlights'), ('goal', 'Goal of the Week'), ('feature', 'Team Feature'), ('saves', 'Best Saves'), ('interview', 'Interview'), ('other', 'Other')], default='highlights', max_length=20, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='videoreview',
            name='description',
            field=models.CharField(blank=True, max_length=300, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='videoreview',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AddField(
            model_name='videoreview',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок (меньше = выше)'),
        ),
        migrations.AlterField(
            model_name='match',
            name='matchday',
            field=models.CharField(blank=True, default='Тур 1', help_text='Например: Тур 1, Групповой этап, 1/4 финала', max_length=50, verbose_name='Тур'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='logo',
            field=models.ImageField(upload_to='sponsors/', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='url',
            field=models.URLField(blank=True, verbose_name='Ссылка на сайт'),
        ),
        migrations.AlterField(
            model_name='videoreview',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='videoreview',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='videoreview',
            name='youtube_id',
            field=models.CharField(help_text='Только ID видео, например: dQw4w9WgXcQ', max_length=20, verbose_name='YouTube ID'),
        ),
        # EMatch and TournamentStanding tables already exist in the DB
        # (created outside migrations). Use SeparateDatabaseAndState so
        # Django records them in migration state without touching the DB.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='EMatch',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('team_a', models.CharField(max_length=100, verbose_name='Команда A')),
                        ('team_b', models.CharField(max_length=100, verbose_name='Команда B')),
                        ('score_a', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)], verbose_name='Счет команды A')),
                        ('score_b', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)], verbose_name='Счет команды B')),
                        ('match_date', models.DateField(verbose_name='Дата матча')),
                        ('match_time', models.TimeField(verbose_name='Время матча')),
                        ('status', models.CharField(choices=[('upcoming', 'Предстоящий'), ('live', 'В прямом эфире'), ('completed', 'Завершен')], default='upcoming', max_length=10, verbose_name='Статус')),
                        ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='Место проведения')),
                        ('tournament_round', models.CharField(blank=True, max_length=100, null=True, verbose_name='Тур/раунд')),
                        ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                        ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                    ],
                    options={
                        'verbose_name': 'Матч',
                        'verbose_name_plural': 'Матчи',
                        'ordering': ['match_date', 'match_time'],
                    },
                ),
                migrations.CreateModel(
                    name='TournamentStanding',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('position', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Position')),
                        ('team_name', models.CharField(max_length=100, verbose_name='Team Name')),
                        ('group', models.CharField(choices=[('A', 'Group A'), ('B', 'Group B')], max_length=1, verbose_name='Group')),
                        ('played', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Matches Played')),
                        ('won', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Won')),
                        ('drawn', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Drawn')),
                        ('lost', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Lost')),
                        ('goals_for', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Goals For (GF)')),
                        ('goals_against', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Goals Against (GA)')),
                        ('points', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Points')),
                        ('form_results', models.JSONField(default=list, verbose_name='Form Results')),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                    ],
                    options={
                        'verbose_name': 'Tournament Standing',
                        'verbose_name_plural': 'Tournament Standings',
                        'ordering': ['group', 'position'],
                    },
                ),
            ],
            database_operations=[],
        ),
    ]
