# Generated by Django 5.2.4 on 2026-01-15 09:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_ematch'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentStanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Position')),
                ('team_name', models.CharField(max_length=100, verbose_name='Team Name')),
                ('group', models.CharField(choices=[('A', 'Group A'), ('B', 'Group B')], max_length=1, verbose_name='Group')),
                ('played', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Matches Played')),
                ('won', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Won')),
                ('drawn', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Drawn')),
                ('lost', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Lost')),
                ('goals_for', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Goals For (GF)')),
                ('goals_against', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Goals Against (GA)')),
                ('points', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Points')),
                ('form_results', models.JSONField(default=list, help_text="List of last 5 results: W (Win), D (Draw), L (Loss). Example: ['W', 'D', 'L', 'W', 'W']", verbose_name='Form Results')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tournament Standing',
                'verbose_name_plural': 'Tournament Standings',
                'ordering': ['group', 'position'],
                'indexes': [models.Index(fields=['group', 'position'], name='core_tourna_group_ebe92a_idx'), models.Index(fields=['group', 'points'], name='core_tourna_group_f70675_idx')],
                'unique_together': {('group', 'position')},
            },
        ),
    ]
