# Generated by Django 6.0.6 on 2026-06-18 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_sponsor_options_alter_videoreview_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VotingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Например: Тур 6', max_length=100, verbose_name='Название')),
                ('is_open', models.BooleanField(default=False, verbose_name='Голосование открыто')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Сессия голосования',
                'verbose_name_plural': 'Сессии голосования',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='tournamentstanding',
            name='form_results',
            field=models.JSONField(default=list, help_text="List of last 5 results: W (Win), D (Draw), L (Loss). Example: ['W', 'D', 'L', 'W', 'W']", verbose_name='Form Results'),
        ),
        # These indexes/constraints already exist in the DB — update state only.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterUniqueTogether(
                    name='tournamentstanding',
                    unique_together={('group', 'position')},
                ),
                migrations.AddIndex(
                    model_name='ematch',
                    index=models.Index(fields=['match_date'], name='core_ematch_match_d_4169d9_idx'),
                ),
                migrations.AddIndex(
                    model_name='ematch',
                    index=models.Index(fields=['status'], name='core_ematch_status_f99510_idx'),
                ),
                migrations.AddIndex(
                    model_name='tournamentstanding',
                    index=models.Index(fields=['group', 'position'], name='core_tourna_group_ebe92a_idx'),
                ),
                migrations.AddIndex(
                    model_name='tournamentstanding',
                    index=models.Index(fields=['group', 'points'], name='core_tourna_group_f70675_idx'),
                ),
            ],
            database_operations=[],
        ),
    ]
